name: C++ CI

on: [ push, pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compiler-name: GCC 13
            cc: gcc-13
            cxx: g++-13
            install-script: |
              sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
              sudo apt update
              sudo apt install -y g++-13
          - compiler-name: Clang 16
            cc: clang-16
            cxx: clang++-16
            install-script: |
              wget https://apt.llvm.org/llvm.sh
              chmod +x llvm.sh
              sudo ./llvm.sh 16

    steps:
      - uses: actions/checkout@v3
      - name: Install compiler (${{ matrix.compiler-name }})
        run: |
          ${{ matrix.install-script }}
      - name: Configure CMake
        run: |
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/${{ matrix.cc }} 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/${{ matrix.cxx }} 100
          cmake -B build -G "Unix Makefiles"
      - name: Build
        run: |
          cmake --build build

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ninja
        run: choco install ninja
      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      - name: Configure CMake with Ninja
        run: cmake -B build -G "Ninja"
      - name: Build with Ninja
        run: cmake --build build
